"""Turn reports/<name>_results.json into a readable report.

Works for the smoke run and, unchanged, for a 1B/3B proxy run.
"""

from __future__ import annotations

import json
import os
import sys

from lib_mixture import ROOT


def main() -> int:
    tag = sys.argv[1] if len(sys.argv) > 1 else "smoke"
    src = os.path.join(ROOT, "reports", f"{tag}_results.json")
    if not os.path.exists(src):
        print(f"no results at {src}")
        return 1
    with open(src, encoding="utf-8") as fh:
        d = json.load(fh)
    res = d["results"]
    lanes = list(res[0]["final"].keys())

    L = []
    a = L.append
    a(f"# Proxy run: `{d['config']}`\n")
    a("_Generated by `scripts/make_smoke_report.py`. Do not edit by hand._\n")
    if tag == "smoke":
        a("**Read this as a check on the harness, not as evidence about V5.** "
          f"{res[0]['params']/1e6:.1f}M parameters and {res[0]['tokens']/1e6:.0f}M tokens per arm "
          "is three orders of magnitude below the scale at which a mixture decision means "
          "anything. What it does show is that the machinery in this repo runs end to end on "
          "real data: curriculum blending, selection against a frozen reference, protected "
          "floors, loss masking, and per-lane evaluation.\n")
    a(f"Device `{d['device']}`, mixture `{d['mixture']}`, "
      f"{len(res)} arms, {res[0]['steps']} steps each.\n")

    a("## Held-out bits per byte, lower is better\n")
    a("| arm | " + " | ".join(lanes) + " | wall (s) |")
    a("|---|" + "---:|" * (len(lanes) + 1))
    for r in res:
        a(f"| {r['arm']} | "
          + " | ".join(f"{r['final'][ln]['bpb']:.3f}" for ln in lanes)
          + f" | {r['wall_seconds']:.0f} |")
    a("")

    base = next((r for r in res if r["arm"].startswith("A")), res[0])
    if len(res) > 1:
        a(f"### Change vs `{base['arm']}` (negative = better than the reference arm)\n")
        a("| arm | " + " | ".join(lanes) + " |")
        a("|---|" + "---:|" * len(lanes))
        for r in res:
            if r["arm"] == base["arm"]:
                continue
            a(f"| {r['arm']} | "
              + " | ".join(f"{r['final'][ln]['bpb'] - base['final'][ln]['bpb']:+.3f}" for ln in lanes)
              + " |")
        a("")

    a("## Realised lane shares\n")
    a("| arm | " + " | ".join(lanes) + " | floor-forced steps | selector overhead |")
    a("|---|" + "---:|" * (len(lanes) + 2))
    for r in res:
        a(f"| {r['arm']} | "
          + " | ".join(f"{r['realized_share'].get(ln, 0)*100:.1f}%" for ln in lanes)
          + f" | {r['floor_forced_steps']} | {r['selector_overhead_frac']*100:.1f}% |")
    a("")

    a("## Gradient-norm monitoring\n")
    a("| arm | mean grad-norm | max spike vs rolling median | warn events | halt events |")
    a("|---|---:|---:|---:|---:|")
    for r in res:
        g = r["gradnorm"]
        a(f"| {r['arm']} | {g['mean']:.3f} | {g['max_mult']:.2f}x | {g['warn']} | {g['halt']} |")
    a("")

    a("## Notes on interpretation\n")
    a("- Bits per byte, not loss per token: Telugu costs ~6.0 bytes per token against ~2.8 for "
      "English in this tokenizer, so per-token loss would flatter the Indic lane by a factor of "
      "two for free.\n")
    a("- The selector reference is trained on `web` and `code` only. That is not a rigged "
      "experiment; it is what a proxy direction built from what the model already does well "
      "looks like in production.\n")
    a("- Selector overhead here is large relative to a real run because the batches are tiny; "
      "the scoring pass is a fixed cost per step that amortises as sequence length and batch "
      "size grow.\n")

    dest = os.path.join(ROOT, "reports", f"{tag}_run.md")
    with open(dest, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
    print("\n".join(L))
    print(f"wrote {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
